#!/usr/bin/with-contenv /bin/bash
# vim:ft=sh

set -Eeuo pipefail

# The openvpn service shares our network namespace, so we end up inheriting
# their iptable rules. This prevents leaks until openvpn is ready.
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

if [[ ! -z "${UMASK:+x}" ]]; then
  umask "$UMASK"
fi

if [[ ! -z "${UIDGID:+x}" ]]; then
  exec s6-setuidgid "$UIDGID" qbittorrent-nox --webui-port="$WEBUI_PORT"
else
  exec qbittorrent-nox --webui-port="$WEBUI_PORT"
fi
