#!/usr/bin/with-contenv /bin/bash
# vim:ft=sh

if [[ ! -z "${UMASK:+x}" ]]; then
  umask "$UMASK"
fi

if [[ ! -z "${UIDGID:+x}" ]]; then
  exec s6-setuidgid "$UIDGID" qbittorrent-nox --webui-port="$WEBUI_PORT"
else
  exec qbittorrent-nox --webui-port="$WEBUI_PORT"
fi
